spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mobile-classroom?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
   # password: qwer1234
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

api:
  minutes: 360
  expire: 12
  moviePath: D:\data\m\
  bannerPath: D:\data\p\
  apkPath: D:\data\d\
  domainAddress: http://42.176.200.33:39146